
- hosts: all
  gather_facts: false
  tasks:
    - name: Synthetic stress
      ansible.builtin.shell: |
        cores=$(nproc)
        load=$(( cores * 5 )) 
        for i in $(seq 1 $load); do
          timeout 60 bash -c 'while :; do :; done' &
        done
        wait
      register: storm
      changed_when: false
      failed_when: storm.rc not in [0,124]
